/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#c0c1ff",
        "primary-fixed-dim": "#c0c1ff",
        "on-tertiary-fixed-variant": "#703700",
        "surface": "#f9f9ff",
        "surface-bright": "#f9f9ff",
        "error-container": "#ffdad6",
        "inverse-surface": "#293040",
        "on-error-container": "#93000a",
        "on-primary-container": "#fffbff",
        "primary-fixed": "#e1e0ff",
        "outline-variant": "#c7c4d7",
        "on-surface-variant": "#464554",
        "tertiary-container": "#b55d00",
        "surface-container-low": "#f1f3ff",
        "on-tertiary-fixed": "#301400",
        "on-secondary-fixed-variant": "#3e4755",
        "on-secondary-fixed": "#121c28",
        "surface-container-high": "#e1e8fd",
        "on-tertiary": "#ffffff",
        "on-primary-fixed-variant": "#2f2ebe",
        "on-primary-fixed": "#07006c",
        "on-secondary-container": "#596372",
        "surface-container": "#e9edff",
        "outline": "#767586",
        "tertiary": "#904900",
        "background": "#f9f9ff",
        "secondary-container": "#d6e0f1",
        "on-secondary": "#ffffff",
        "surface-container-highest": "#dce2f7",
        "on-background": "#141b2b",
        "on-tertiary-container": "#fffbff",
        "error": "#ba1a1a",
        "surface-tint": "#494bd6",
        "tertiary-fixed": "#ffdcc5",
        "surface-variant": "#dce2f7",
        "primary": "#4648d4",
        "primary-container": "#6063ee",
        "on-surface": "#141b2b",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#bdc7d8",
        "on-primary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "secondary": "#555f6d",
        "surface-dim": "#d3daef",
        "secondary-fixed": "#d9e3f4",
        "inverse-on-surface": "#edf0ff",
        "tertiary-fixed-dim": "#ffb783"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "margin-desktop": "40px",
        "3xl": "64px",
        "2xl": "48px",
        "margin-mobile": "16px",
        "base": "4px",
        "gutter": "16px",
        "md": "16px",
        "xs": "8px",
        "lg": "24px",
        "xl": "32px",
        "sm": "12px"
      },
      maxWidth: {
        "sm": "24rem",
        "md": "28rem",
        "lg": "32rem",
        "xl": "36rem",
        "2xl": "42rem",
        "3xl": "48rem",
        "4xl": "56rem",
        "5xl": "64rem",
        "6xl": "72rem",
        "7xl": "80rem"
      },
      fontFamily: {
        "headline-lg-mobile": ["Inter"],
        "body-md": ["Inter"],
        "price-lg": ["Inter"],
        "body-sm": ["Inter"],
        "headline-md": ["Inter"],
        "label-md": ["Inter"],
        "display-lg": ["Inter"],
        "headline-lg": ["Inter"],
        "body-lg": ["Inter"]
      },
      fontSize: {
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "price-lg": ["20px", { "lineHeight": "28px", "fontWeight": "700" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }]
      }
    }
  },
  plugins: [],
}
